### ISSUE TITLE
Comment about code and idea for json output

### ISSUE THREAD

**Issue by lgfausak** [xenogenesi/task-spooler#3]
I just ran across the original code and your fork.  I really like the code.  It is pretty old, but it still compiles and works for me.  Have you tried to contact Lluís Batlle i Rossell?  I looked at the original code and could not figure out how to thank him/her for the great utility.    Anyway, I was thinking it would be a good addition to add a json output and maybe even a json api.  I haven't worked with C in a while, but I could take a stab at the json output if it might be useful.

**Comment by xenogenesi** [comment]
I contacted Lluìs when this repository was created, take a better look to [task spooler's home page](http://vicerveza.homeunix.net/~viric/soft/ts/) the email address is at the end of the footer.
