### ISSUE TITLE
tsp not working with bash function

### ISSUE THREAD

**Issue by port22** [xenogenesi/task-spooler#5]
Is there any way to get tsp work with a predefined function?
When I call the function with tsp, it is immediately finished.

```
$ function foo () { sleep 10; }
$ export -f foo
$ tsp foo; tsp -l
```

`11   finished   /tmp/ts-out.77x57o   -1       0.00/0.00/0.00 foo`

Maybe the function foo has not been triggered at all.

I thought about making it different, but I would have to redesign a hell of a lot things to work again then.

**Comment by xenogenesi** [comment]
@port22 an easy way would be to call your functions from an executable script

**Comment by port22** [comment]
I do call the function from within a bash script.  Annyways  Seem to be possible

**Comment by port22** [comment]
I do call the function from within a bash script.  Annyways  Seem to be possible
